// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: E:\workspace_android\workspace_androidstudio\RocketSinghPillion\protos\biker.proto
package biker;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class AssignedRequestId extends Message {
  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_MERCHANT_ID = "";
  public static final String DEFAULT_TIME_ID = "";

  @ProtoField(tag = 1, type = STRING)
  public final String merchant_id;

  @ProtoField(tag = 2, type = STRING)
  public final String time_id;

  public AssignedRequestId(String merchant_id, String time_id) {
    this.merchant_id = merchant_id;
    this.time_id = time_id;
  }

  private AssignedRequestId(Builder builder) {
    this(builder.merchant_id, builder.time_id);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AssignedRequestId)) return false;
    AssignedRequestId o = (AssignedRequestId) other;
    return equals(merchant_id, o.merchant_id)
        && equals(time_id, o.time_id);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = merchant_id != null ? merchant_id.hashCode() : 0;
      result = result * 37 + (time_id != null ? time_id.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<AssignedRequestId> {

    public String merchant_id;
    public String time_id;

    public Builder() {
    }

    public Builder(AssignedRequestId message) {
      super(message);
      if (message == null) return;
      this.merchant_id = message.merchant_id;
      this.time_id = message.time_id;
    }

    public Builder merchant_id(String merchant_id) {
      this.merchant_id = merchant_id;
      return this;
    }

    public Builder time_id(String time_id) {
      this.time_id = time_id;
      return this;
    }

    @Override
    public AssignedRequestId build() {
      return new AssignedRequestId(this);
    }
  }
}
