// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: E:\workspace_android\workspace_androidstudio\RocketSinghPillion\protos\MobileResponse.proto
package mobileresponse;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REPEATED;

public final class AllRequestResponse extends Message {
  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_STATUS = "";
  public static final List<CompleteRequestDetails> DEFAULT_COMPLETE_REQUEST = Collections.emptyList();

  @ProtoField(tag = 1, type = STRING)
  public final String status;

  @ProtoField(tag = 2, label = REPEATED, messageType = CompleteRequestDetails.class)
  public final List<CompleteRequestDetails> complete_request;

  public AllRequestResponse(String status, List<CompleteRequestDetails> complete_request) {
    this.status = status;
    this.complete_request = immutableCopyOf(complete_request);
  }

  private AllRequestResponse(Builder builder) {
    this(builder.status, builder.complete_request);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof AllRequestResponse)) return false;
    AllRequestResponse o = (AllRequestResponse) other;
    return equals(status, o.status)
        && equals(complete_request, o.complete_request);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = status != null ? status.hashCode() : 0;
      result = result * 37 + (complete_request != null ? complete_request.hashCode() : 1);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<AllRequestResponse> {

    public String status;
    public List<CompleteRequestDetails> complete_request;

    public Builder() {
    }

    public Builder(AllRequestResponse message) {
      super(message);
      if (message == null) return;
      this.status = message.status;
      this.complete_request = copyOf(message.complete_request);
    }

    public Builder status(String status) {
      this.status = status;
      return this;
    }

    public Builder complete_request(List<CompleteRequestDetails> complete_request) {
      this.complete_request = checkForNulls(complete_request);
      return this;
    }

    @Override
    public AllRequestResponse build() {
      return new AllRequestResponse(this);
    }
  }
}
