// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: E:\workspace_android\workspace_androidstudio\RocketSinghPillion\protos\MobileResponse.proto
package mobileresponse;

import biker.BikerLocation;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import java.util.Collections;
import java.util.List;

import static com.squareup.wire.Message.Datatype.STRING;
import static com.squareup.wire.Message.Label.REPEATED;

public final class BikersNearByResponse extends Message {
  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_STATUS = "";
  public static final List<BikerLocation> DEFAULT_BIKERLOCATIONS = Collections.emptyList();

  @ProtoField(tag = 1, type = STRING)
  public final String status;

  @ProtoField(tag = 2, label = REPEATED, messageType = BikerLocation.class)
  public final List<BikerLocation> bikerLocations;

  public BikersNearByResponse(String status, List<BikerLocation> bikerLocations) {
    this.status = status;
    this.bikerLocations = immutableCopyOf(bikerLocations);
  }

  private BikersNearByResponse(Builder builder) {
    this(builder.status, builder.bikerLocations);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof BikersNearByResponse)) return false;
    BikersNearByResponse o = (BikersNearByResponse) other;
    return equals(status, o.status)
        && equals(bikerLocations, o.bikerLocations);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = status != null ? status.hashCode() : 0;
      result = result * 37 + (bikerLocations != null ? bikerLocations.hashCode() : 1);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<BikersNearByResponse> {

    public String status;
    public List<BikerLocation> bikerLocations;

    public Builder() {
    }

    public Builder(BikersNearByResponse message) {
      super(message);
      if (message == null) return;
      this.status = message.status;
      this.bikerLocations = copyOf(message.bikerLocations);
    }

    public Builder status(String status) {
      this.status = status;
      return this;
    }

    public Builder bikerLocations(List<BikerLocation> bikerLocations) {
      this.bikerLocations = checkForNulls(bikerLocations);
      return this;
    }

    @Override
    public BikersNearByResponse build() {
      return new BikersNearByResponse(this);
    }
  }
}
