// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: E:\workspace_android\workspace_androidstudio\RocketSinghPillion\protos\MobileResponse.proto
package mobileresponse;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import request.PaymentDetails;
import request.TripData;

import static com.squareup.wire.Message.Datatype.STRING;

public final class CompleteRequestDetails extends Message {
  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_TIME_ID = "";
  public static final String DEFAULT_CUSTOMER_NAME = "";
  public static final String DEFAULT_BIKER_NAME = "";
  public static final String DEFAULT_BIKER_NUMBER_PLATE = "";
  public static final String DEFAULT_REQUEST_STATUS = "";

  @ProtoField(tag = 1, type = STRING)
  public final String time_id;

  @ProtoField(tag = 2, type = STRING)
  public final String customer_name;

  @ProtoField(tag = 3, type = STRING)
  public final String biker_name;

  @ProtoField(tag = 4, type = STRING)
  public final String biker_number_plate;

  @ProtoField(tag = 5, type = STRING)
  public final String request_status;

  @ProtoField(tag = 6)
  public final TripData tripData;

  @ProtoField(tag = 7)
  public final PaymentDetails paymentDetails;

  public CompleteRequestDetails(String time_id, String customer_name, String biker_name, String biker_number_plate, String request_status, TripData tripData, PaymentDetails paymentDetails) {
    this.time_id = time_id;
    this.customer_name = customer_name;
    this.biker_name = biker_name;
    this.biker_number_plate = biker_number_plate;
    this.request_status = request_status;
    this.tripData = tripData;
    this.paymentDetails = paymentDetails;
  }

  private CompleteRequestDetails(Builder builder) {
    this(builder.time_id, builder.customer_name, builder.biker_name, builder.biker_number_plate, builder.request_status, builder.tripData, builder.paymentDetails);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof CompleteRequestDetails)) return false;
    CompleteRequestDetails o = (CompleteRequestDetails) other;
    return equals(time_id, o.time_id)
        && equals(customer_name, o.customer_name)
        && equals(biker_name, o.biker_name)
        && equals(biker_number_plate, o.biker_number_plate)
        && equals(request_status, o.request_status)
        && equals(tripData, o.tripData)
        && equals(paymentDetails, o.paymentDetails);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = time_id != null ? time_id.hashCode() : 0;
      result = result * 37 + (customer_name != null ? customer_name.hashCode() : 0);
      result = result * 37 + (biker_name != null ? biker_name.hashCode() : 0);
      result = result * 37 + (biker_number_plate != null ? biker_number_plate.hashCode() : 0);
      result = result * 37 + (request_status != null ? request_status.hashCode() : 0);
      result = result * 37 + (tripData != null ? tripData.hashCode() : 0);
      result = result * 37 + (paymentDetails != null ? paymentDetails.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<CompleteRequestDetails> {

    public String time_id;
    public String customer_name;
    public String biker_name;
    public String biker_number_plate;
    public String request_status;
    public TripData tripData;
    public PaymentDetails paymentDetails;

    public Builder() {
    }

    public Builder(CompleteRequestDetails message) {
      super(message);
      if (message == null) return;
      this.time_id = message.time_id;
      this.customer_name = message.customer_name;
      this.biker_name = message.biker_name;
      this.biker_number_plate = message.biker_number_plate;
      this.request_status = message.request_status;
      this.tripData = message.tripData;
      this.paymentDetails = message.paymentDetails;
    }

    public Builder time_id(String time_id) {
      this.time_id = time_id;
      return this;
    }

    public Builder customer_name(String customer_name) {
      this.customer_name = customer_name;
      return this;
    }

    public Builder biker_name(String biker_name) {
      this.biker_name = biker_name;
      return this;
    }

    public Builder biker_number_plate(String biker_number_plate) {
      this.biker_number_plate = biker_number_plate;
      return this;
    }

    public Builder request_status(String request_status) {
      this.request_status = request_status;
      return this;
    }

    public Builder tripData(TripData tripData) {
      this.tripData = tripData;
      return this;
    }

    public Builder paymentDetails(PaymentDetails paymentDetails) {
      this.paymentDetails = paymentDetails;
      return this;
    }

    @Override
    public CompleteRequestDetails build() {
      return new CompleteRequestDetails(this);
    }
  }
}
