// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: E:\workspace_android\workspace_androidstudio\RocketSinghPillion\protos\MobileResponse.proto
package mobileresponse;

import biker.BikerLocation;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

/**
 * Used as response when a pillion/merchant makes a request for biker
 */
public final class MakeRequestResponse extends Message {
  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_STATUS = "";
  public static final String DEFAULT_TIME_ID = "";

  @ProtoField(tag = 1, type = STRING)
  public final String status;

  @ProtoField(tag = 2, type = STRING)
  public final String time_id;

  @ProtoField(tag = 3)
  public final BikerLocation bikerLocation;

  public MakeRequestResponse(String status, String time_id, BikerLocation bikerLocation) {
    this.status = status;
    this.time_id = time_id;
    this.bikerLocation = bikerLocation;
  }

  private MakeRequestResponse(Builder builder) {
    this(builder.status, builder.time_id, builder.bikerLocation);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof MakeRequestResponse)) return false;
    MakeRequestResponse o = (MakeRequestResponse) other;
    return equals(status, o.status)
        && equals(time_id, o.time_id)
        && equals(bikerLocation, o.bikerLocation);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = status != null ? status.hashCode() : 0;
      result = result * 37 + (time_id != null ? time_id.hashCode() : 0);
      result = result * 37 + (bikerLocation != null ? bikerLocation.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<MakeRequestResponse> {

    public String status;
    public String time_id;
    public BikerLocation bikerLocation;

    public Builder() {
    }

    public Builder(MakeRequestResponse message) {
      super(message);
      if (message == null) return;
      this.status = message.status;
      this.time_id = message.time_id;
      this.bikerLocation = message.bikerLocation;
    }

    public Builder status(String status) {
      this.status = status;
      return this;
    }

    public Builder time_id(String time_id) {
      this.time_id = time_id;
      return this;
    }

    public Builder bikerLocation(BikerLocation bikerLocation) {
      this.bikerLocation = bikerLocation;
      return this;
    }

    @Override
    public MakeRequestResponse build() {
      return new MakeRequestResponse(this);
    }
  }
}
