// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: E:\workspace_android\workspace_androidstudio\RocketSinghPillion\protos\request.proto
package request;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.DOUBLE;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.INT64;
import static com.squareup.wire.Message.Datatype.STRING;

public final class PaymentDetails extends Message {
  private static final long serialVersionUID = 0L;

  public static final Double DEFAULT_TRIP_DISTANCE = 0D;
  public static final Double DEFAULT_TRIP_COST = 0D;
  public static final Double DEFAULT_TRIP_TIME = 0D;
  public static final Double DEFAULT_PROMO_CODE = 0D;
  public static final Long DEFAULT_START_TIME = 0L;
  public static final Double DEFAULT_PAYMENT_MADE = 0D;
  public static final String DEFAULT_PAYMENT_MODE = "";
  public static final Integer DEFAULT_SURGE_PRICING_MULTIPLIER = 0;

  @ProtoField(tag = 1, type = DOUBLE)
  public final Double trip_distance;

  @ProtoField(tag = 2, type = DOUBLE)
  public final Double trip_cost;

  @ProtoField(tag = 3, type = DOUBLE)
  public final Double trip_time;

  @ProtoField(tag = 4, type = DOUBLE)
  public final Double promo_code;

  @ProtoField(tag = 5, type = INT64)
  public final Long start_time;

  @ProtoField(tag = 6, type = DOUBLE)
  public final Double payment_made;

  @ProtoField(tag = 7, type = STRING)
  public final String payment_mode;

  @ProtoField(tag = 8, type = INT32)
  public final Integer surge_pricing_multiplier;

  public PaymentDetails(Double trip_distance, Double trip_cost, Double trip_time, Double promo_code, Long start_time, Double payment_made, String payment_mode, Integer surge_pricing_multiplier) {
    this.trip_distance = trip_distance;
    this.trip_cost = trip_cost;
    this.trip_time = trip_time;
    this.promo_code = promo_code;
    this.start_time = start_time;
    this.payment_made = payment_made;
    this.payment_mode = payment_mode;
    this.surge_pricing_multiplier = surge_pricing_multiplier;
  }

  private PaymentDetails(Builder builder) {
    this(builder.trip_distance, builder.trip_cost, builder.trip_time, builder.promo_code, builder.start_time, builder.payment_made, builder.payment_mode, builder.surge_pricing_multiplier);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof PaymentDetails)) return false;
    PaymentDetails o = (PaymentDetails) other;
    return equals(trip_distance, o.trip_distance)
        && equals(trip_cost, o.trip_cost)
        && equals(trip_time, o.trip_time)
        && equals(promo_code, o.promo_code)
        && equals(start_time, o.start_time)
        && equals(payment_made, o.payment_made)
        && equals(payment_mode, o.payment_mode)
        && equals(surge_pricing_multiplier, o.surge_pricing_multiplier);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = trip_distance != null ? trip_distance.hashCode() : 0;
      result = result * 37 + (trip_cost != null ? trip_cost.hashCode() : 0);
      result = result * 37 + (trip_time != null ? trip_time.hashCode() : 0);
      result = result * 37 + (promo_code != null ? promo_code.hashCode() : 0);
      result = result * 37 + (start_time != null ? start_time.hashCode() : 0);
      result = result * 37 + (payment_made != null ? payment_made.hashCode() : 0);
      result = result * 37 + (payment_mode != null ? payment_mode.hashCode() : 0);
      result = result * 37 + (surge_pricing_multiplier != null ? surge_pricing_multiplier.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<PaymentDetails> {

    public Double trip_distance;
    public Double trip_cost;
    public Double trip_time;
    public Double promo_code;
    public Long start_time;
    public Double payment_made;
    public String payment_mode;
    public Integer surge_pricing_multiplier;

    public Builder() {
    }

    public Builder(PaymentDetails message) {
      super(message);
      if (message == null) return;
      this.trip_distance = message.trip_distance;
      this.trip_cost = message.trip_cost;
      this.trip_time = message.trip_time;
      this.promo_code = message.promo_code;
      this.start_time = message.start_time;
      this.payment_made = message.payment_made;
      this.payment_mode = message.payment_mode;
      this.surge_pricing_multiplier = message.surge_pricing_multiplier;
    }

    public Builder trip_distance(Double trip_distance) {
      this.trip_distance = trip_distance;
      return this;
    }

    public Builder trip_cost(Double trip_cost) {
      this.trip_cost = trip_cost;
      return this;
    }

    public Builder trip_time(Double trip_time) {
      this.trip_time = trip_time;
      return this;
    }

    public Builder promo_code(Double promo_code) {
      this.promo_code = promo_code;
      return this;
    }

    public Builder start_time(Long start_time) {
      this.start_time = start_time;
      return this;
    }

    public Builder payment_made(Double payment_made) {
      this.payment_made = payment_made;
      return this;
    }

    public Builder payment_mode(String payment_mode) {
      this.payment_mode = payment_mode;
      return this;
    }

    public Builder surge_pricing_multiplier(Integer surge_pricing_multiplier) {
      this.surge_pricing_multiplier = surge_pricing_multiplier;
      return this;
    }

    @Override
    public PaymentDetails build() {
      return new PaymentDetails(this);
    }
  }
}
