// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: E:\workspace_android\workspace_androidstudio\RocketSinghPillion\protos\MobileRequest.proto
package mobilerequest;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.DOUBLE;

public final class LatLngProto extends Message {
  private static final long serialVersionUID = 0L;

  public static final Double DEFAULT_LATITUDE = 0D;
  public static final Double DEFAULT_LONGITUDE = 0D;

  @ProtoField(tag = 1, type = DOUBLE)
  public final Double latitude;

  @ProtoField(tag = 2, type = DOUBLE)
  public final Double longitude;

  public LatLngProto(Double latitude, Double longitude) {
    this.latitude = latitude;
    this.longitude = longitude;
  }

  private LatLngProto(Builder builder) {
    this(builder.latitude, builder.longitude);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof LatLngProto)) return false;
    LatLngProto o = (LatLngProto) other;
    return equals(latitude, o.latitude)
        && equals(longitude, o.longitude);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = latitude != null ? latitude.hashCode() : 0;
      result = result * 37 + (longitude != null ? longitude.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<LatLngProto> {

    public Double latitude;
    public Double longitude;

    public Builder() {
    }

    public Builder(LatLngProto message) {
      super(message);
      if (message == null) return;
      this.latitude = message.latitude;
      this.longitude = message.longitude;
    }

    public Builder latitude(Double latitude) {
      this.latitude = latitude;
      return this;
    }

    public Builder longitude(Double longitude) {
      this.longitude = longitude;
      return this;
    }

    @Override
    public LatLngProto build() {
      return new LatLngProto(this);
    }
  }
}
