// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: E:\workspace_android\workspace_androidstudio\RocketSinghPillion\protos\MobileRequest.proto
package mobilerequest;

import biker.BikersNearBy;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;
import request.TripData;

import static com.squareup.wire.Message.Datatype.DOUBLE;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Datatype.STRING;

public final class NewRequest extends Message {
  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_PHONENO = "";
  public static final String DEFAULT_NAME = "";
  public static final Integer DEFAULT_APP_TYPE = 0;
  public static final Double DEFAULT_CUR_LATITUDE = 0D;
  public static final Double DEFAULT_CUR_LONGITUDE = 0D;
  public static final String DEFAULT_CUST_DEVICE_TOKEN = "";

  @ProtoField(tag = 1, type = STRING)
  public final String phoneNo;

  @ProtoField(tag = 2, type = STRING)
  public final String name;

  @ProtoField(tag = 3, type = INT32)
  public final Integer app_type;

  @ProtoField(tag = 4)
  public final TripData trip_data;

  @ProtoField(tag = 5)
  public final BikersNearBy bikerNearBy;

  @ProtoField(tag = 6, type = DOUBLE)
  public final Double cur_latitude;

  @ProtoField(tag = 7, type = DOUBLE)
  public final Double cur_longitude;

  @ProtoField(tag = 8, type = STRING)
  public final String cust_device_token;

  public NewRequest(String phoneNo, String name, Integer app_type, TripData trip_data, BikersNearBy bikerNearBy, Double cur_latitude, Double cur_longitude, String cust_device_token) {
    this.phoneNo = phoneNo;
    this.name = name;
    this.app_type = app_type;
    this.trip_data = trip_data;
    this.bikerNearBy = bikerNearBy;
    this.cur_latitude = cur_latitude;
    this.cur_longitude = cur_longitude;
    this.cust_device_token = cust_device_token;
  }

  private NewRequest(Builder builder) {
    this(builder.phoneNo, builder.name, builder.app_type, builder.trip_data, builder.bikerNearBy, builder.cur_latitude, builder.cur_longitude, builder.cust_device_token);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof NewRequest)) return false;
    NewRequest o = (NewRequest) other;
    return equals(phoneNo, o.phoneNo)
        && equals(name, o.name)
        && equals(app_type, o.app_type)
        && equals(trip_data, o.trip_data)
        && equals(bikerNearBy, o.bikerNearBy)
        && equals(cur_latitude, o.cur_latitude)
        && equals(cur_longitude, o.cur_longitude)
        && equals(cust_device_token, o.cust_device_token);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = phoneNo != null ? phoneNo.hashCode() : 0;
      result = result * 37 + (name != null ? name.hashCode() : 0);
      result = result * 37 + (app_type != null ? app_type.hashCode() : 0);
      result = result * 37 + (trip_data != null ? trip_data.hashCode() : 0);
      result = result * 37 + (bikerNearBy != null ? bikerNearBy.hashCode() : 0);
      result = result * 37 + (cur_latitude != null ? cur_latitude.hashCode() : 0);
      result = result * 37 + (cur_longitude != null ? cur_longitude.hashCode() : 0);
      result = result * 37 + (cust_device_token != null ? cust_device_token.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<NewRequest> {

    public String phoneNo;
    public String name;
    public Integer app_type;
    public TripData trip_data;
    public BikersNearBy bikerNearBy;
    public Double cur_latitude;
    public Double cur_longitude;
    public String cust_device_token;

    public Builder() {
    }

    public Builder(NewRequest message) {
      super(message);
      if (message == null) return;
      this.phoneNo = message.phoneNo;
      this.name = message.name;
      this.app_type = message.app_type;
      this.trip_data = message.trip_data;
      this.bikerNearBy = message.bikerNearBy;
      this.cur_latitude = message.cur_latitude;
      this.cur_longitude = message.cur_longitude;
      this.cust_device_token = message.cust_device_token;
    }

    public Builder phoneNo(String phoneNo) {
      this.phoneNo = phoneNo;
      return this;
    }

    public Builder name(String name) {
      this.name = name;
      return this;
    }

    public Builder app_type(Integer app_type) {
      this.app_type = app_type;
      return this;
    }

    public Builder trip_data(TripData trip_data) {
      this.trip_data = trip_data;
      return this;
    }

    public Builder bikerNearBy(BikersNearBy bikerNearBy) {
      this.bikerNearBy = bikerNearBy;
      return this;
    }

    public Builder cur_latitude(Double cur_latitude) {
      this.cur_latitude = cur_latitude;
      return this;
    }

    public Builder cur_longitude(Double cur_longitude) {
      this.cur_longitude = cur_longitude;
      return this;
    }

    public Builder cust_device_token(String cust_device_token) {
      this.cust_device_token = cust_device_token;
      return this;
    }

    @Override
    public NewRequest build() {
      return new NewRequest(this);
    }
  }
}
