// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: E:\workspace_android\workspace_androidstudio\RocketSinghBiker\protos\MobileRequest.proto
package mobilerequest;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class BikerStatusData extends Message {
  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_BIKER_ID = "";
  public static final String DEFAULT_BIKER_STATUS_FLAG = "";

  @ProtoField(tag = 1, type = STRING)
  public final String biker_id;

  @ProtoField(tag = 2, type = STRING)
  public final String biker_status_flag;

  public BikerStatusData(String biker_id, String biker_status_flag) {
    this.biker_id = biker_id;
    this.biker_status_flag = biker_status_flag;
  }

  private BikerStatusData(Builder builder) {
    this(builder.biker_id, builder.biker_status_flag);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof BikerStatusData)) return false;
    BikerStatusData o = (BikerStatusData) other;
    return equals(biker_id, o.biker_id)
        && equals(biker_status_flag, o.biker_status_flag);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = biker_id != null ? biker_id.hashCode() : 0;
      result = result * 37 + (biker_status_flag != null ? biker_status_flag.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<BikerStatusData> {

    public String biker_id;
    public String biker_status_flag;

    public Builder() {
    }

    public Builder(BikerStatusData message) {
      super(message);
      if (message == null) return;
      this.biker_id = message.biker_id;
      this.biker_status_flag = message.biker_status_flag;
    }

    public Builder biker_id(String biker_id) {
      this.biker_id = biker_id;
      return this;
    }

    public Builder biker_status_flag(String biker_status_flag) {
      this.biker_status_flag = biker_status_flag;
      return this;
    }

    @Override
    public BikerStatusData build() {
      return new BikerStatusData(this);
    }
  }
}
