// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: E:\workspace_android\workspace_androidstudio\RocketSinghBiker\protos\MobileRequest.proto
package mobilerequest;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoEnum;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.BOOL;
import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.STRING;

public final class CancellationDetails extends Message {
  private static final long serialVersionUID = 0L;

  public static final BikerState DEFAULT_BIKER_STATE = BikerState.ON_WAY_TO_PICKUP_ORDER;
  public static final Boolean DEFAULT_IS_CANCELLED = false;
  public static final String DEFAULT_CANCELLED_BY = "";
  public static final String DEFAULT_CANCELLATION_REASON = "";

  @ProtoField(tag = 1, type = ENUM)
  public final BikerState biker_state;

  @ProtoField(tag = 2, type = BOOL)
  public final Boolean is_cancelled;

  @ProtoField(tag = 3, type = STRING)
  public final String cancelled_by;

  @ProtoField(tag = 4, type = STRING)
  public final String cancellation_reason;

  public CancellationDetails(BikerState biker_state, Boolean is_cancelled, String cancelled_by, String cancellation_reason) {
    this.biker_state = biker_state;
    this.is_cancelled = is_cancelled;
    this.cancelled_by = cancelled_by;
    this.cancellation_reason = cancellation_reason;
  }

  private CancellationDetails(Builder builder) {
    this(builder.biker_state, builder.is_cancelled, builder.cancelled_by, builder.cancellation_reason);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof CancellationDetails)) return false;
    CancellationDetails o = (CancellationDetails) other;
    return equals(biker_state, o.biker_state)
        && equals(is_cancelled, o.is_cancelled)
        && equals(cancelled_by, o.cancelled_by)
        && equals(cancellation_reason, o.cancellation_reason);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = biker_state != null ? biker_state.hashCode() : 0;
      result = result * 37 + (is_cancelled != null ? is_cancelled.hashCode() : 0);
      result = result * 37 + (cancelled_by != null ? cancelled_by.hashCode() : 0);
      result = result * 37 + (cancellation_reason != null ? cancellation_reason.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<CancellationDetails> {

    public BikerState biker_state;
    public Boolean is_cancelled;
    public String cancelled_by;
    public String cancellation_reason;

    public Builder() {
    }

    public Builder(CancellationDetails message) {
      super(message);
      if (message == null) return;
      this.biker_state = message.biker_state;
      this.is_cancelled = message.is_cancelled;
      this.cancelled_by = message.cancelled_by;
      this.cancellation_reason = message.cancellation_reason;
    }

    public Builder biker_state(BikerState biker_state) {
      this.biker_state = biker_state;
      return this;
    }

    public Builder is_cancelled(Boolean is_cancelled) {
      this.is_cancelled = is_cancelled;
      return this;
    }

    public Builder cancelled_by(String cancelled_by) {
      this.cancelled_by = cancelled_by;
      return this;
    }

    public Builder cancellation_reason(String cancellation_reason) {
      this.cancellation_reason = cancellation_reason;
      return this;
    }

    @Override
    public CancellationDetails build() {
      return new CancellationDetails(this);
    }
  }

  public enum BikerState
      implements ProtoEnum {
    ON_WAY_TO_PICKUP_ORDER(1),
    REACHED_MERCHANT(2),
    STARTED_DELIVERY(3),
    FINISHED_DELIVERY(4);

    private final int value;

    private BikerState(int value) {
      this.value = value;
    }

    @Override
    public int getValue() {
      return value;
    }
  }
}
