// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: E:\workspace_android\workspace_androidstudio\RocketSinghBiker\protos\MobileResponse.proto
package mobileresponse;

import biker.BikerProfile;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.STRING;

public final class LoginResponseBiker extends Message {
  private static final long serialVersionUID = 0L;

  public static final String DEFAULT_STATUS = "";

  @ProtoField(tag = 1, type = STRING)
  public final String status;

  @ProtoField(tag = 2)
  public final BikerProfile biker_profile;

  public LoginResponseBiker(String status, BikerProfile biker_profile) {
    this.status = status;
    this.biker_profile = biker_profile;
  }

  private LoginResponseBiker(Builder builder) {
    this(builder.status, builder.biker_profile);
    setBuilder(builder);
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof LoginResponseBiker)) return false;
    LoginResponseBiker o = (LoginResponseBiker) other;
    return equals(status, o.status)
        && equals(biker_profile, o.biker_profile);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = status != null ? status.hashCode() : 0;
      result = result * 37 + (biker_profile != null ? biker_profile.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<LoginResponseBiker> {

    public String status;
    public BikerProfile biker_profile;

    public Builder() {
    }

    public Builder(LoginResponseBiker message) {
      super(message);
      if (message == null) return;
      this.status = message.status;
      this.biker_profile = message.biker_profile;
    }

    public Builder status(String status) {
      this.status = status;
      return this;
    }

    public Builder biker_profile(BikerProfile biker_profile) {
      this.biker_profile = biker_profile;
      return this;
    }

    @Override
    public LoginResponseBiker build() {
      return new LoginResponseBiker(this);
    }
  }
}
